############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Docs"
url = "/docs"
weight = 2

[[main]]
name = "Adapters"
url = "/docs/adapters"
weight = 3

[[main]]
name = "Countries"
url = "/docs/adapters/countries"
weight = 4

# footer menu
[[footer]]
name = "Docs"
url = "/docs"
weight = 1

[[footer]]
name = "Adapters"
url = "/docs/adapters"
weight = 2

[[footer]]
name = "GitHub"
url = "https://github.com/joeblew999/plat-nuki"
weight = 3
